#footprint: [[0.05,0.3], [0.05,-0.3], [-0.44,-0.05], [-0.45,0.05]]
robot_radius: 0.001
publish_frequency: 8.0
subscribe_to_updates: true

#map_topic: map

#observation_sources: laser_scan_sensor, point_cloud_sensor
#laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: true}
#global_frame: map
#robot_base_frame: base_footprint
transform_tolerance: 0.2
always_send_full_costmap: true
plugins: 
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}

inflation:
    inflation_radius:  0.5
    cost_scaling_factor: 2.0
#static_layer:
#   map_topic: map
#    observation_sources: point_cloud_sensor
#    observation_sources: laser_scan_sensor

#    laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}
#    point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: true}

obstacle_layer:
    obstacle_range: 1.5 #1.5
    raytrace_range: 2.5 #2.0
    enabled: true
    obstacle_range: 3
    raytrace_range: 3.5
    inflation_radius: 0.13
    track_unknown_space: false
    combination_method: 1 
    observation_sources: point_cloud_sensor
#    observation_sources: laser_scan_sensor
#    laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}
    point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /tape_cloud, marking: true, clearing: true}
    
cost_factor: 0.55
neutral_cost: 66
lethal_cost: 253