global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0
  width: 10
  height: 20
  rolling_window: true
  resolution: 0.05
  plugins: 
    - {name: static_layer,type: "costmap_2d::StaticLayer"}
    - {name: static,type: "costmap_2d::StaticLayer"}
    - {name: inflation,type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
#    - {name: simple_layer,      type: "simple_layer_namespace::SimpleLayer"}
#    - {name: grid_layer,      type: "simple_layer_namespace::GridLayer"}
    
    
  static:
     lethal_cost_threshold: 94
     static_map: false
     track_unknown_space: true
     map_topic: map
     unknown_cost_value: 1
     trinary_costmap: false
     use_maximum: false  
