local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05
  plugins: 
    - {name: static_layer,type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,type: "costmap_2d::InflationLayer"}
#    - {name: simple_layer,      type: "simple_layer_namespace::SimpleLayer"}
#    - {name: grid_layer,      type: "simple_layer_namespace::GridLayer"}
    
    
    
#----------------CUSTOM_CREATED_LAYER------------------------------------
#- {name: simple_layer,      type: "simple_layer_namespace::SimpleLayer"}
#- {name: grid_layer,      type: "simple_layer_namespace::GridLayer"}