global_costmap:
    #footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
    robot_radius: 0.18
    footprint_padding: 0.02
    transform_tolerance: 1.0
    update_frequency: 4
    publish_frequency: 0.5
    
    global_frame: map
    robot_base_frame: base_footprint
    
    width: 50
    height: 50
    resolution: 0.075

    rolling_window: false
    track_unknown_space: true

    plugins: 
        - {name: static,           type: "costmap_2d::StaticLayer"}            
        - {name: sensor,           type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,        type: "costmap_2d::InflationLayer"}

    static:        
        map_topic: /map
        #map_topic: /map
        subscribe_to_updates: true

    sensor:
        observation_sources: laser_scan_sensor
        laser: {sensor_frame: base_link, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true, obstacle_range: 2.0, raytrace_range: 5.0, inf_is_valid: true}

    inflation:
        inflation_radius: 1.72
        cost_scaling_factor: 2.53
