#For full documentation of the parameters in this file, and a list of all the
#parameters available for DWAPlannerROS, please see
#http://www.ros.org/wiki/dwa_local_planner
DWAPlannerROS:
  holonomic_robot: true
  
  acc_lim_trans: 4.23
  acc_lim_theta: 2.5
  acc_lim_x: 3
  acc_lim_y: 3

  max_vel_x: 5.5  #0.5
  min_vel_x: -5.5  #-0.5

  max_vel_y: 5.5  #0.5
  min_vel_y: -5.5  #-0.5

  max_vel_trans: 5.6  #0.6
  min_vel_trans: 5.1  #0.1

  max_vel_theta: 5.6  #0.6
  min_vel_theta: 5.1  #0.1

  sim_time: 1.0
  sim_granularity: 0.02
  vx_samples: 13
  vy_samples: 10
  vtheta_samples: 19

  goal_distance_bias: 20
  path_distance_bias: 32
  occdist_scale: 0.02

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0

  scaling_speed: 0.3  #0.3
  max_scaling_factor: 0.5

  xy_goal_tolerance: 0.1 # m
  yaw_goal_tolerance: 0.2 # rad
  latch_xy_goal_tolerance: false
  prune_plan: true

 #rot_stopped_vel: 0.01
 #trans_stopped_vel: 0.01