talos:
  widowxl_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
    gains:
      arm_joint_0:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_joint_1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_joint_2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_joint_3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_joint_4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  widowxl_gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - arm_joint_6
      - arm_joint_7
    gains:
      arm_joint_6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      arm_joint_7:
        p: 100
        d: 1
        i: 1
        i_clamp: 1