# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: widowxl_arm_
  joint_model_group_pose: navigation
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint_0
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_6
    - arm_joint_7
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  - name: /talos/widowxl_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
  - name: /talos/widowxl_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_joint_6
      - arm_joint_7